# Generated by Django 3.2.3 on 2024-03-12 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты'
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты'
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги'
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipes',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(
                related_name='favorited_recipes', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(
                related_name='recipes_in_cart', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
